[workspace]
members = ["verso", "versoview_messages", "versoview_build"]

[workspace.package]
version = "0.0.9"
edition = "2024"
license = "Apache-2.0 OR MIT"
homepage = "https://versotile.org/verso"
repository = "https://github.com/versotile-org/verso"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
ipc-channel = "0.20"
bincode = "1"
url = { version = "2.5.2", features = ["serde"] }
log = "0.4"
headers = "0.4"
http = "1"
uuid = { version = "1", features = ["v4", "serde"] }
dpi = { version = "0.1", features = ["serde"] }

[package]
name = "versoview"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "An innovative web browser"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.versotile.org/verso"
categories = ["web-programming"]

[package.metadata.packager]
name = "verso"
product-name = "verso"
identifier = "org.versotile.verso"
version = "0.0.1"
before-each-package-command = "python etc/package_libs.py"
resources = [
  "resources",
  "icons",
  "target/release/build/**/libEGL.dll",
  "target/release/build/**/libGLESv2.dll",
  "target/release/lib",
]
icons = ["icons/icon256x256.png", "icons/icon.ico"]

[package.metadata.packager.nsis]
appdata-paths = ["$LOCALAPPDATA/$IDENTIFIER"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
]

[features]
#default = ["vello_cpu"]
bluetooth = [
   # "bluetooth_traits",
   # "dep:bluetooth",
  #  "constellation/bluetooth",
  #  "constellation_traits/bluetooth",
   # "script/bluetooth",
  #  "script_traits/bluetooth",
]
#background_hang_monitor = ["background_hang_monitor/sampler"]
#vello = ["libservo/vello"]
#vello_cpu = ["libservo/vello_cpu"]
packager = ["dep:cargo-packager-resource-resolver"]
flatpak = []
tracing = []

[build-dependencies]
cfg_aliases = "0.2"

[dependencies]
arboard = "3.4.0"
crossbeam-channel = "0.5"
env_logger = "0.11"
euclid = "0.22"
getopts = "0.2.17"
# gleam = "0.15"
# glow = "0.16"
# glutin = "0.32.0"
# glutin-winit = "0.5.0"
ipc-channel = { workspace = true }
keyboard-types = { version = "0.8.0", features = ["webdriver", "serde"] }
log = { workspace = true }
raw-window-handle = { version = "0.6", features = ["std"] }
rustls = { version = "0.23", default-features = false, features = ["aws-lc-rs"] }
sparkle = "0.1.26"
thiserror = "2"
winit = { version = "0.30", features = ["rwh_06"] }
dpi = { workspace = true }
url = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
versoview_messages = { path = "./versoview_messages" }
serde = { workspace = true }
serde_json = "1.0"
bincode = { workspace = true }
mime = "0.3"
uuid = { workspace = true }
rfd = "0.15"
bitflags = "2.9"
surfman = "0.11"
# Servo repo crates
servo = " 0.1.0"
servo-constellation-traits = "0.1.0"
servo-embedder-traits = "0.1.0"
servo-geometry = "0.1.0"
servo-base = "0.1.0"
servo-net = "0.1.0"
servo-net-traits = "0.1.0"
servo-paint-api = "0.1.0"
servo-url = "0.1.0"
servo-media-player = "0.1.0"
webrender_api = "0.68.0"

# Packager feature
cargo-packager-resource-resolver = { version = "0.1.1", features = [
  "auto-detect-format",
], optional = true }

[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "ios"), not(target_os = "android")))'.dependencies]
notify-rust = { version = "4.11.5", features = ["images"] }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
notify-rust = "4.11.5"
muda = "0.15"

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc2 = "0.5"
objc2-foundation = { version = "0.2.2", features = ["NSThread"] }
objc2-app-kit = { version = "0.2", features = [
  "NSView",
  "NSResponder",
  "NSWindow",
] }

[[test]]
name = "general"
harness = false

[profile.release-lto]
inherits = "release"
lto = true

# Tell clippy to allow e.g. #[cfg(macos)]
[lints.rust]
unexpected_cfgs = "allow"
